name: Publish CI

on:
# ONLY CARE ABOUT RELEASES - AS TESTS ARE FAILING
#  pull_request:
#    branches: [ master ]
  release:
    types:
    - published

  # ALLOW MANUAL RUNS
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
#       AGAIN ONLY THE RELEASE
#        os: [macos-latest, ubuntu-latest, windows-latest]
        os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install the package dependencies
      run: npm install
        
    - name: Install vsce
      run: npm i vsce -g
    
#   TESTS ARE FAILING - DOING MORE RESEARCH
#    - run: xvfb-run -a npm test
#      if: runner.os == 'Linux'
#      name: Test extension
      
#    - run: npm test
#      if: runner.os != 'Linux'
#      name: Test extension

    - name: Publish - vsce
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: vsce publish --yarn
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Install ovsx
      run: npm i ovsx -g
      
    - name: Publish - ovsx
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: ovsx publish
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
