name: Publish CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
    - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install the package dependencies
      run: npm install
        
    - name: Install vsce
      run: npm i vsce -g
    
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
      name: Test extension
      
    - run: npm test
      if: runner.os != 'Linux'
      name: Test extension
      
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: vsce publish --yarn
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
